#!/bin/bash
# Switches this dev container into Kerberos/GSSAPI SSO mode: enables the Apache <Location> block
# for svc/sso_login.py and switches authentication.module to passthru. Run this only when you
# specifically want to test Kerberos SSO -- it replaces the documented default cobbler/cobbler
# password login system-wide for as long as it's active.
#
# Requires setup-kerberos.sh to have already run (done automatically by setup-supervisor.sh) and
# `make install` to have already installed cobbler.conf to /etc/apache2/vhosts.d/.
set -e

KEYTAB=/etc/apache2/cobbler.keytab
APACHE_CONF=/etc/apache2/vhosts.d/cobbler.conf

if [ ! -f "$KEYTAB" ]; then
    echo "error: $KEYTAB not found -- run setup-kerberos.sh first" >&2
    exit 1
fi
if [ ! -f "$APACHE_CONF" ]; then
    echo "error: $APACHE_CONF not found -- run 'make install' first" >&2
    exit 1
fi

# Uncomment the commented-out SSO <Location> block, and point it at this container's keytab path
# (the shipped example in config/apache/cobbler.conf uses an illustrative RHEL-style path).
sed -i \
    -e '/^#WSGIScriptAlias \/cobbler-sso\/login/ s/^#//' \
    -e '/^#<Location \/cobbler-sso\/login>/,/^#<\/Location>/ s/^#//' \
    -e "s#GssapiCredStore keytab:.*#GssapiCredStore keytab:${KEYTAB}#" \
    "$APACHE_CONF"

a2enmod auth_gssapi
# On openSUSE, a2enmod only updates /etc/sysconfig/apache2's APACHE_MODULES; the actual
# LoadModule directives in /etc/apache2/loadmodule.conf are only regenerated by
# /usr/sbin/start_apache2's wrapper script, which supervisord bypasses (it execs
# `httpd -D FOREGROUND` directly, per docker/develop/supervisord/conf.d/httpd.conf). Without this,
# a2enmod silently has no effect and Apache never actually loads mod_auth_gssapi.
GSSAPI_MODULE_PATH=$(find /usr/lib64/apache2 /usr/lib/apache2 -name 'mod_auth_gssapi.so' 2>/dev/null | head -n1)
if [ -z "$GSSAPI_MODULE_PATH" ]; then
    echo "error: mod_auth_gssapi.so not found -- is apache2-mod_auth_gssapi installed?" >&2
    exit 1
fi
if ! grep -q '^LoadModule auth_gssapi_module' /etc/apache2/loadmodule.conf; then
    echo "LoadModule auth_gssapi_module ${GSSAPI_MODULE_PATH}" >> /etc/apache2/loadmodule.conf
fi

sed -i 's/^module = authentication.configfile/module = authentication.passthru/' /etc/cobbler/modules.conf

supervisorctl restart httpd
supervisorctl restart cobblerd

echo "Kerberos SSO enabled."
echo "On the host: kinit testuser@COBBLER.TEST (password: testpass), then:"
echo "  curl --negotiate -u : http://localhost/cobbler-sso/login"
