version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "no changelog"
    groups:
      dependabot:
        applies-to: version-updates
        patterns:
          - "*"
