Documentation:
- changed-files:
  - any-glob-to-any-file: 'docs/*'

Tests:
- changed-files:
  - any-glob-to-any-file: 'tests/*'
  - any-glob-to-any-file: 'system-tests/*'

CI:
- changed-files:
  - any-glob-to-any-file: '.github/*'

Packaging:
- changed-files:
  - any-glob-to-any-file: '.obs/*'
  - any-glob-to-any-file: 'cobbler.spec'
  - any-glob-to-any-file: 'debian/*'

API:
- changed-files:
  - any-glob-to-any-file: 'cobbler/api.py'
  - any-glob-to-any-file: 'cobbler/remote.py'
  - any-glob-to-any-file: 'services.py'
