=head1 NAME

koan stands for "kickstart-over-a-network" and allows for both network provisioning of new virtualized guests and destructive provisioning of any existing system.  For use with a boot-server configured with 'cobbler'.

=head1 SYNOPSIS

koan --server=<host> --list-profiles

koan --server=<host> --list-systems

koan --virt --server=<host> --profile=<name> [--virtname=<name>]

koan --virt --server=<host> --system=<name> [--virtname=<name>]

koan --replace-self --server=<host> --profile=<name>

koan --replace-self --server=<host> --system=<name>

koan --replace-self --server=<host>

=head1 DESCRIPTION

When invoked, koan requests profile information from a remote boot server that has been configured with cobbler.   What koan does with the profile data depends on whether it was invoked with --virt or --replace-self.

For --virt, cobbler will create new virtualized guests on a machine in accordance to the orders from cobbler.  You can then, once finished, use "virsh" and "xm" commands on the guest.  Cobbler automatically names domains based on their mac addresses.  To install using a more descriptive name, specify one with --virtname.

For re-kickstarting ('--replace-self'), cobbler will reprovisioning the system, blowing away any current data and replacing it with the results of a network install.  Specify a specific item from cobbler with --system or --profile, otherwise cobbler will try to see if there is a cobbler system record that matches a MAC address on the system.

=head1 NOTES FOR USERS OF COBBLER TEMPLATING

Cobbler contains an advanced templating feature that allows a single kickstart file to be customized on a per-system basis.  See the cobbler manpage for more details.

If you have system specific customizations in your kickstarts and have cobbler system definitions defined server side for those systems, use --system and not --profile.

=head1 ADDITIONAL

Consult the man page for cobbler for more information.

=head1 AUTHOR

Michael DeHaan <mdehaan@redhat.com>


