=head1 NAME

xen-net-install is run on a Xen dom0 as root to network provision
new Xen domU's.  It is expected the remote server has been configured 
with 'bootconf sync' and has xen profiles made available.

=head1 SYNOPSIS

xen-net-install [--server=ip|hostname] --profiles=[profile1,profile2,...]

=head1 DESCRIPTION

xen-net-install requests named profiles from a remote boot server.
Configuration parameters, kernels, and initrds are automatically downloaded
according to the local machine from the server.  New systems are then
automatically created by performing the equivalent of a command line
"xenguest-install".  Ultimately it allows installing the same Xen
image multiple times without thinking about where to get images or
what parameters to feed xenguest-install.

=head1 EXAMPLE

Installing two Xen instances without any further user input:

xen-guest-install --server=bootserver.example.com --profiles=webserver,dbserver

Assumes bootconf commands have already been run on bootserver.example.com.
See 'man bootconf'.

=head1 AUTHOR

Michael DeHaan <mdehaan@redhat.com>


