import unittest


# TODO: test remote.background_aclsetup()
# TODO: test remote.background_buildiso()
# TODO: test remote.background_dlcontent()
# TODO: test remote.background_hardlink()
# TODO: test remote.background_import()
# TODO: test remote.background_replicate()
# TODO: test remote.background_reposync()
# TODO: test remote.background_validateks()
# TODO: test remote.clear_system_logs()
# TODO: test remote.disable_netboot()
# TODO: test remote.extended_version()
# TODO: test remote.find_items_paged()
# TODO: test remote.find_system_by_dns_name()
# TODO: test remote.generatescript()
# TODO: test remote.get_<item>_as_rendered()
# TODO: test remote.get_<item>s_since()
# TODO: test remote.get_authn_module_name()
# TODO: test remote.get_blended_data()
# TODO: test remote.get_config_dataa()
# TODO: test remote.get_repos_compatible_with_profile()
# TODO: test remote.get_status()
# TODO: test remote.get_template_file_for_profile()
# TODO: test remote.get_template_file_for_system()
# TODO: test remote.is_kickstart_in_use()
# TODO: test remote.logout()
# TODO: test remote.modify_setting()
# TODO: test remote.read_or_write_kickstart_template()
# TODO: test remote.read_or_write_snippet()
# TODO: test remote.run_install_triggers()
# TODO: test remote.version()
# TODO: test remote.xapi_object_edit()

if __name__ == '__main__':
    unittest.main()
