#!/bin/sh -e
# Bootstrap the OS for system tests
# If you adjust anything in this file please check also with the "../prelude" script

server=192.168.1.1
bridge=pxe
etc_qemu=$(test -e /etc/qemu-kvm && echo /etc/qemu-kvm || echo /etc/qemu)

ip link add ${bridge} type bridge
ip address add ${server}/24 dev ${bridge}
ip link set up dev ${bridge}

mkdir -p ${etc_qemu}
echo allow ${bridge} >>${etc_qemu}/bridge.conf

# This is specific for the openSUSE environment
cat >/etc/cobbler/settings.yaml <<-EOF
server: ${server}
next_server_v4: ${server}
manage_dhcp: true
manage_dhcp_v4: true
manage_dhcp_v6: false
power_management_default_type: 'ipmilan'
tftpboot_location: '/srv/tftpboot'
webdir: '/srv/www/cobbler'
EOF

supervisorctl restart cobblerd

cobbler mkloaders
