#!/bin/sh -e
# Bootstrap a RHEL-based host

server=192.168.1.1
bridge=pxe

# Install the necessary packages
dnf install -y dhcp-server grub2 qemu-kvm

# Create the bridge interface
ip link add ${bridge} type bridge
ip link set up dev ${bridge}
ip address add ${server}/24 dev ${bridge}

# Allow QEMU to use the bridge
echo "allow ${bridge}" >>/etc/qemu-kvm/bridge.conf

# Configure Cobbler
cat >/etc/cobbler/settings.d/system-tests.settings <<-EOF
	server: ${server}
	next_server_v4: ${server}
	manage_dhcp: true
	manage_dhcp_v6: false
	power_management_default_type: 'ipmilan'
EOF

# Create the Grub images
/usr/share/cobbler/bin/mkgrub.sh
