#!/bin/sh
#
# cobblerd    Cobbler helper daemon
#
# chkconfig: 345 99 99 
# description:  This is a daemon that provides remote cobbler info to koan
#               clients and also logs installer yslog activitity. 
#
# processname: /usr/bin/cobblerd

# Sanity checks.
[ -x /usr/bin/cobblerd ] || exit 0

# Source function library.
. /etc/rc.d/init.d/functions

RETVAL=0

start() {
    echo -n $"Starting cobbler daemon: "
    if test -f /var/lock/subsys/cobblerd ; then
        echo_failure
        echo
        return 1
    fi
    /usr/bin/cobblerd
    RETVAL=$?
    echo_success
    echo
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/cobblerd
    return $RETVAL
}


stop() {
    echo -n $"Stopping cobbler daemon: "
    if ! test -f /var/lock/subsys/cobblerd ; then
        echo_failure
        echo
        return 1
    fi
    pkill cobblerd
    RETVAL=$?
    rm /var/lock/subsys/cobblerd
    echo_success
    echo
    return $RETVAL
}

mystatus() {
    if test -f /var/lock/subsys/cobblerd ; then
        echo "cobbblerd is running..."
        return 0
    fi
    echo "cobblerd is stopped"
    echo
    return 0
}

# See how we were called.
case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        mystatus
        RETVAL=$?
        ;;
    restart)
        stop
        start
        ;;
    condrestart)
        if [ -f /var/lock/subsys/cobblerd ]; then
            stop
            start
        fi
        ;;
    reload)
        echo "can't reload configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        ;;
esac
exit $RETVAL

