#!/bin/sh
#
# cobblerd    Cobbler helper daemon
###################################

# LSB header

### BEGIN INIT INFO
# Provides: cobblerd
# Required-Start: network, xinetd, httpd
# Default-Start: 3 4 5
# Short-Description: daemon for libvirt virtualization API
# Description: This is a daemon that a provides remote cobbler API
#              and status tracking
### END INIT INFO

# chkconfig header

# chkconfig: 345 99 99 
# description:  This is a daemon that provides a remote cobbler API
#               and status tracking
#
# processname: /usr/bin/cobblerd

# Sanity checks.
[ -x /usr/bin/cobblerd ] || exit 0

DEBIAN_VERSION=/etc/debian_version
# Source function library.
if [ -e $DEBIAN_VERSION ]; then

	. /etc/init.d/functions
else
	. /etc/rc.d/init.d/functions
fi

SERVICE=cobblerd
PROCESS=cobblerd
CONFIG_ARGS=" "
if [ -e $DEBIAN_VERSION ]; then
	LOCKFILE=/var/lock/$SERVICE
else
	LOCKFILE=/var/lock/subsys/$SERVICE
fi

RETVAL=0

start() {
    echo -n $"Starting cobbler daemon: "
    daemon --check $SERVICE $PROCESS --daemon $CONFIG_ARGS
    RETVAL=$?
    echo
    [ $RETVAL -eq 0 ] && touch $LOCKFILE
    return $RETVAL
}

stop() {
    echo -n $"Stopping cobbler daemon: "
    killproc $PROCESS
    RETVAL=$?
    echo
    if [ $RETVAL -eq 0 ]; then
	rm -f $LOCKFILE
        rm -f /var/run/$SERVICE.pid
    fi
}

restart() {
   stop
   start
}

# See how we were called.
case "$1" in
    start|stop|restart)
        $1
        ;;
    status)
        status $PROCESS
        RETVAL=$?
        ;;
    condrestart)
        [ -f $LOCKFILE ] && restart || :
        ;;
    reload)
        echo "can't reload configuration, you have to restart it"
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|condrestart|reload}"
        exit 1
        ;;
esac
exit $RETVAL

