#!/usr/bin/env bash
# Check that Cobbler can rename systems

source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

cobbler distro add --name fake --arch x86_64 --kernel ${fake_kernel} \
	--initrd ${fake_initramfs}
cobbler profile add --name fake --distro fake
cobbler system add --name testbed --profile fake
cobbler system rename --name testbed --newname testbed-renamed

[ ! -e ${path_collections}/systems/testbed.json ]
[   -e ${path_collections}/systems/testbed-renamed.json ]
