#!/bin/bash
# Check that cobbler-settings can modify value from the YAML

# Arrange
source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

TEST_CONFIG="${tmp}/settings-dict.yaml"
EXPECTED_CONFIG="${tmp}/settings-expected.yaml"
cat <<-END >$TEST_CONFIG
kernel_options:
 from_cobbler: true
END

cat <<-END >$EXPECTED_CONFIG
# Cobbler settings file
# Docs for this file can be found at: https://cobbler.readthedocs.io/en/latest/cobbler-conf.html

kernel_options: {}
END

TEST_KEY="kernel_options"
TEST_VALUE=""

# Act
cobbler-settings -c "$TEST_CONFIG" modify -k "$TEST_KEY" -v "$TEST_VALUE"

# Assert
diff $TEST_CONFIG $EXPECTED_CONFIG
