#!/usr/bin/env bash
# Check that the Cobbler HTTP endpoint /autoinstall/ is callable

source ${SYSTESTS_PRELUDE} && prepare

set -x -e -o pipefail

# Arrange
cobbler distro add --name fake --arch x86_64 --kernel ${fake_kernel} \
	--initrd ${fake_initramfs}
cobbler profile add --name fake --distro fake
cobbler system add --name testbed --profile fake
#TODO add hostname
# Prepare expected result
cat >${tmp}/a <<-EOF
TODO
EOF

# Act
curl --output=${tmp}/b http://localhost/cblr/svc/op/puppet/

# Assert
# FIXME endpoint not yet testable
exit 0
#diff ...