"""
Fields For Cobbler Systems

Copyright 2009, Red Hat, Inc
Michael DeHaan <mdehaan@redhat.com>
and others

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
02110-1301  USA
"""

def get_fields():
   return {
       'name': {
           'type'    :'text',
           'valtype' :'str',
           'label'   :'Name',
           'example' :'Example: vanhalen',
           'size'    :'128',
           'width'   :'150px',
           'value'   :'',
           'default' :'',
           'opts'    :'',
           'setopts' :'disabled="true"',
           'editable':True,
       },
       'ctime': {
           'type'    :'label',
           'valtype' :'str',
           'label'   :'Created',
           'value'   :'',
           'default' :'',
           'editable':False,
       },
       'mtime': {
           'type'    :'label',
           'valtype' :'str',
           'label'   :'Last Modified',
           'value'   :'',
           'default' :'',
           'editable':False,
       },
       'comment': {
           'type'    : 'textarea',
           'valtype' : 'str',
           'label'   : 'Comment',
           'example' : 'This is a free-form description field',
           'rows'    : '5',
           'cols'    : '30',
           'width'   : '400px',
           'value'   : '',
           'default' : '',
           'opts'    : '',
           'setopts' : '',
           'editable': True,
        },
        'netboot_enabled': {
           'type'    : 'checkbox',
           'valtype' : 'str',
           'label'   : 'Netboot Enabled',
           'example' : 'For PXE setups, select to boot the profile below for the system.<br/>De-select to boot the system from local disk.',
           'value'   : '',
           'default' : '',
           'list'    : [],
           'opts'    : '',
           'editable': True,
        },
        'profile': {
           'type'    : 'select',
           'valtype' : 'str',
           'label'   : 'Profile',
           'example' : 'What profile should be installed on this system?',
           'value'   : '',
           'default' : '',
           'list'    : [],
           'opts'    : '',
           'editable': True,
        },
        'ks_meta': {
           'type'     : 'text',
           'valtype'  : 'str',
           'label'    : 'Kickstart Metadata',
           'example'  : 'Example: dog=fido gnome=yes',
           'size'     : '255',
           'width'    : '400px',
           'value'    : '',
           'default'  : '',
           'opts'     : '',
           'setopts'  : '',
           'editable' : True,
        },
        'kernel_options': {
           'type'    :'text',
           'valtype' :'str',
           'label'   :'Kernel Options',
           'example' :'Example: noipv6 magic=foo',
           'size'    :'255',
           'width'   :'400px',
           'value'   :'',
           'default' :'',
           'opts'    :'',
           'setopts' :'',
           'editable':True,
        },
        'kernel_options_post': {
           'type'    :'text',
           'valtype' :'str',
           'label'   :'Kernel Options Post',
           'example' :'Example: clocksource=pit nosmp noapic nolapic',
           'size'    :'255',
           'width'   :'400px',
           'value'   :'',
           'default' :'',
           'opts'    :'',
           'setopts' :'',
           'editable':True,
        },
        'hostname': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Hostname',
            'example' :'Example: "vanhalen.example.org".  Used for /etc/sysconfig/network.',
            'size'    :'64',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'netedit',
            'editable':True,
        },
        'gateway': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Gateway',
            'example' :'Example: "192.168.1.11".  For use with static IP configs.',
            'size'    :'64',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'netedit',
            'editable':True,
        },
        'name_servers': {
            'type'    :'text',
            'valtype' :'list',
            'label'   :'Name Servers',
            'example' :'Name servers, space delimited, if not provided by DHCP',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'netedit',
            'editable':True,
        },
        'name_servers_search': {
            'type'    :'text',
            'valtype' :'list',
            'label'   :'Name Servers Search Path',
            'example' :'Name servers search path, space delimited, if not provided by DHCP',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'netedit',
            'editable':True,
        },
        'virt_file_size': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Virt Disk (GB)',
            'example' :'For virtual installs only, the virtual disk size in GB',
            'size'    :'5',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'virtedit',
            'editable':True,
        },
        'virt_ram': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Virt RAM (MB)',
            'example' :'For virtual installs only, the RAM size in MB',
            'size'    :'5',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'virtedit',
            'editable':True,
        },
        'virt_auto_boot': {
            'type'    :'checkbox',
            'valtype' :'str',
            'label'   :'Virt Autoboot',
            'example' :'For virtual installs only, enable/disable VM auto start',
            'size'    :'5',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'virtedit',
            'editable':True,
        },
        'virt_type': {
            'type'    :'radio',
            'valtype' :'str',
            'label'   :'Virt Type',
            'example' :'For virtual installs only, the virtualization technology koan should use',
            'value'   :'',
            'default' :'',
            'list'    :(['auto','Any'],['xenpv','Xen(pv)'],['xenfv','Xen(fv)'],['qemu','KVM/qemu'],['vmware','VMWare Server'],['vmwarew','VMWare WkStn']),
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'virtedit',
            'editable':True,
        },
        'virt_path': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Virt Path',
            'example' :'For virtual installs only, sets koan\'s storage preferences, read manpage or leave blank',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'virtedit',
            'editable':True,
        },
        'virt_cpus': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Virt CPUs',
            'example' :'For virtual installs only, how many virtual CPUs?  This is an integer',
            'size'    :'255',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'virtedit',
            'editable':True,
        },
        'power_address': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Power Address',
            'example' :'Example: hostname-mgmt.example.org',
            'size'    :'255',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'poweredit',
            'editable':True,
        },
        'power_id': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Power Id',
            'example' :'Plug number or blade name, if applicable.',
            'size'    :'255',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'poweredit',
            'editable':True,
        },
        'power_user': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Power User',
            'example' :'Power management username, if device requires one.',
            'size'    :'255',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'poweredit',
            'editable':True,
        },
        'power_pass': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Power Password',
            'example' :'Power management password, if device requires one.',
            'size'    :'255',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'tdclass' :'poweredit',
            'editable':True,
        },
        'server': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Server Override',
            'example' :'Use this server for kickstarts, not the value in settings. Normally this should be left blank',
            'size'    :'128',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'editable':True,
        },
        'redhat_management_key': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Management Key',
            'example' :'Registration key for RHN, Satellite, or Spacewalk',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'editable':True,
        },
        'redhat_management_server': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'Management Server',
            'example' :'RHN, Satellite, or Spacewalk server',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'editable':True,
        },
        'mgmt_classes': {
            'type'    :'text',
            'valtype' :'list',
            'label'   :'Management Classes',
            'example' :'Management classes (space delimited) for use with external configuration management system',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'editable':True,
        },
        'owners': {
            'type'    :'text',
            'valtype' :'list',
            'label'   :'Access Allowed For',
            'example' :'Applies only if using authz_ownership module, space delimited',
            'size'    :'255',
            'width'   :'400px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'editable':True,
        },
        'interfaces': {
            'type'    :'dict',
            'fields'  : {
                'key': {
                    'type'    :'text',
                    'valtype' :'str',
                    'label'   :'Interface name',
                    'example' :'Example: eth0, bond0, eth0.11, bond0.12',
                    'size'    :'64',
                    'width'   :'150px',
                    'value'   :'',
                    'default' :'',
                    'opts'    :'',
                    'setopts' :'',
                    'tdclass' :'nicedit',
                    'editable':True,
                },
                'ip_address': {
                    'type'    :'text',
                    'valtype' :'str',
                    'label'   :'IP',
                    'example' :'Example: 192.168.10.15',
                    'size'    :'64',
                    'width'   :'150px',
                    'value'   :'',
                    'default' :'',
                    'opts'    :'',
                    'setopts' :'',
                    'tdclass' :'nicedit',
                    'editable':True,
                },
            },
        'dhcp_tag': {
            'type'    :'text',
            'valtype' :'str',
            'label'   :'DHCP Tag',
            'example' :'Specifies alternative DHCP configuration, see manpage or leave blank',
            'size'    :'128',
            'width'   :'150px',
            'value'   :'',
            'default' :'',
            'opts'    :'',
            'setopts' :'',
            'editable':True,
        },
    },
}
