# FIXME: header

def get_fields():
   return {
     'name': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Name',
       'example' :'Example: RHEL-5-i386',
       'size'    :'128',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'disabled="true"',
       'order'   :0,
       'editable':True,
     },
     'ctime': {
       'type'    :'label',
       'valtype' :'str',
       'label'   :'Created',
       'value'   :'',
       'default' :'',
       'order'   :1,
       'editable':False,
     },
     'mtime': {
       'type'    :'label',
       'valtype' :'str',
       'label'   :'Last Modified',
       'value'   :'',
       'default' :'',
       'order'   :2,
       'editable':False,
     },
     'comment': {
       'type'    :'textarea',
       'valtype' :'str',
       'label'   :'Comment',
       'example' :'This is a free-form description field',
       'rows'    :'5',
       'cols'    :'30',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :3,
       'editable':True,
     },
     'distro': {
       'type'    :'select',
       'valtype' :'str',
       'label'   :'Parent Distro',
       'example' :'Parent distribution',
       'value'   :'',
       'default' :'',
       'list'    :[],
       'opts'    :'',
       'order'   :4,
       'editable':True,
     },
     'parent': {
       'type'    :'select',
       'valtype' :'str',
       'label'   :'Parent Object',
       'example' :'Object to inherit from',
       'value'   :'',
       'default' :'',
       'list'    :[],
       'opts'    :'',
       'order'   :4,
       'editable':True,
     },
     'kickstart': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Kickstart File',
       'example' :'An absolute filesystem path to a template (preferred), or http:// URL',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :5,
       'editable':True,
    },
     'kernel_options': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Kernel Options',
       'example' :'Example: noipv6 magic=foo',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :6,
       'editable':True,
     },
     'kernel_options_post': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Kernel Options Post',
       'example' :'Example: clocksource=pit nosmp noapic nolapic',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :7,
       'editable':True,
     },
     'ks_meta': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Kickstart Metadata',
       'example' :'Example: dog=fido gnome=yes foo bar',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :8,
       'editable':True,
     },
     'enable_menu': {
       'type'    :'checkbox',
       'valtype' :'str',
       'label'   :'Enable Menu',
       'example' :'Show this profile in the PXE boot menu?',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :9,
       'editable':True,
     },
     'name_servers': {
       'type'    :'text',
       'valtype' :'list',
       'label'   :'Name Servers',
       'example' :'Name servers, space delimited, if not provided by DHCP',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :10,
       'editable':True,
     },
     'name_servers_search': {
       'type'    :'text',
       'valtype' :'list',
       'label'   :'Name Servers Search Path',
       'example' :'Name servers search path, space delimited, if not provided by DHCP',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :11,
       'editable':True,
     },
     'virt_file_size': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Virt Disk (GB)',
       'example' :'For virtual installs only, the virtual disk size in GB',
       'size'    :'5',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :12,
       'editable':True,
     },
     'virt_ram': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Virt RAM (MB)',
       'example' :'For virtual installs only, the RAM size in MB',
       'size'    :'5',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :13,
       'editable':True,
     },
     'virt_auto_boot': {
       'type'    :'checkbox',
       'valtype' :'str',
       'label'   :'Virt Autoboot',
       'example' :'For virtual installs only, enable/disable VM auto start',
       'size'    :'5',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :14,
       'editable':True,
     },
     'virt_type': {
       'type'    :'radio',
       'valtype' :'str',
       'label'   :'Virt Type',
       'example' :'For virtual installs only, the virtualization technology koan should use',
       'value'   :'',
       'default' :'',
       'list'    :(['auto','Any'],['xenpv','Xen(pv)'],['xenfv','Xen(fv)'],['qemu','KVM/qemu'],['vmware','VMWare Server'],['vmwarew','VMWare WkStn']),
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :15,
       'editable':True,
     },
     'virt_path': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Virt Path',
       'example' :'For virtual installs only, sets koan\'s storage preferences, read manpage or leave blank',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :16,
       'editable':True,
     },
     'virt_bridge': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Virt Bridge',
       'example' :'For virtual installs only, overrides the virtual networking bridge choice in settings',
       'size'    :'255',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :17,
       'editable':True,
     },
     'virt_cpus': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Virt CPUs',
       'example' :'For virtual installs only, how many virtual CPUs?  This is an integer',
       'size'    :'255',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'tdclass' :'virtedit',
       'order'   :18,
       'editable':True,
     },
     'repos': {
       'type'    :'select',
       'valtype' :'str',
       'label'   :'Yum Repos',
       'example' :'Select yum repos to automatically assign to the target system',
       'value'   :'',
       'default' :'',
       'list'    :[],
       'opts'    :'multiple="1"',
       'setopts' :'',
       'order'   :19,
       'editable':True,
     },
     'dhcp_tag': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'DHCP Tag',
       'example' :'Specifies alternative DHCP configuration, see manpage or leave blank',
       'size'    :'128',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :20,
       'editable':True,
     },
     'server': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Server Override',
       'example' :'Use this server for kickstarts, not the value in settings. Normally this should be left blank',
       'size'    :'128',
       'width'   :'150px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :21,
       'editable':True,
     },
     'redhat_management_key': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Management Key',
       'example' :'Registration key for RHN, Satellite, or Spacewalk',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :22,
       'editable':True,
     },
     'redhat_management_server': {
       'type'    :'text',
       'valtype' :'str',
       'label'   :'Management Server',
       'example' :'RHN, Satellite, or Spacewalk server',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :23,
       'editable':True,
     },
     'mgmt_classes': {
       'type'    :'text',
       'valtype' :'list',
       'label'   :'Management Classes',
       'example' :'Management classes (space delimited) for use with external configuration management system',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :24,
       'editable':True,
     },
     'owners': {
       'type'    :'text',
       'valtype' :'list',
       'label'   :'Access Allowed For',
       'example' :'Applies only if using authz_ownership module, space delimited',
       'size'    :'255',
       'width'   :'400px',
       'value'   :'',
       'default' :'',
       'opts'    :'',
       'setopts' :'',
       'order'   :25,
       'editable':True,
     },
   }
