#!/usr/bin/python

"""
Koan wrapper script.  See 'man koan' for details.

Copyright 2006 Red Hat, Inc.
Michael DeHaan <mdehaan@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import sys

# ok, about this sys.path voodoo...
# ordinarily cobbler and koan are intended for FC-5/6 and derivs
# this makes "cobbler enchant" using FC-5 RPMs work on Centos as well
# when installed with --nodeps. yes, I know it looks evil.
# though since "enchant" is there to blow away a system, evil is allowed.
sys.path.append("/usr/lib/python2.3/site-packages")
sys.path.append("/usr/lib64/python2.3/site-packages")
import koan.koan as app
sys.exit(app.main() or 0)
