#!/usr/bin/python

import yaml # PyYAML version
import urlgrabber
import sys

if __name__ == "__main__":
   hostname = None
   try:
      hostname = sys.argv[1]
   except:
      print "usage: cobbler-ext-nodes <hostname>"

   if hostname is not None:
       conf = open("/etc/cobbler/settings")
       config = yaml.load(conf.read());
       conf.close()
       url = "http://%s:%s/cblr/svc/op/puppet/hostname/%s" % (config["server"], config["http_port"], hostname)
       print urlgrabber.urlread(url)


