#!/usr/bin/python

"""
cobbler-register wrapper script.  See 'man cobbler-register' for details.

Copyright 2009 Red Hat, Inc and Others.
Michael DeHaan <michael.dehaan AT gmail>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import sys
import koan.register as register
sys.exit(register.main() or 0)
