#!/usr/bin/python

"""
Wrapper for cobbler

Copyright 2006, Red Hat, Inc
Michael DeHaan <mdehaan@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import cobbler.cobbler as app
import sys

PROFILING = False

if PROFILING:
    print "** PROFILING **"
    import hotshot, hotshot.stats
    prof = hotshot.Profile("cobbler.prof")
    prof.runcall(app.main)
    prof.close()
    stats = hotshot.stats.load("cobbler.prof")
    stats.strip_dirs()
    stats.sort_stats('time')
    print "** REPORT **"
    stats.print_stats(100)
    sys.exit(0)
else:
    sys.exit(app.main())

