#!/usr/bin/python

"""
Koan wrapper script.  See 'man koan' for details.

Copyright 2006-2009 Red Hat, Inc.
Michael DeHaan <mdehaan@redhat.com>

This software may be freely redistributed under the terms of the GNU
general public license.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
"""

import sys
import koan.app as app
sys.exit(app.main() or 0)
